name: lean_builder
description: A streamlined Dart build system that applies lean principles to minimize waste and maximize speed. Designed for developers who value efficiency and performance.
version: 0.1.0
repository: https://github.com/Milad-Akarie/lean_builder
platforms:
  macos:
  linux:
  windows:

topics:
  - build
  - build-system
  - dart-build-system
  - code-generation
  - codegen

executables:
  lean_builder:

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  _fe_analyzer_shared: ^88.0.0
  analyzer: ">=7.4.0 <9.0.0"
  args: ^2.7.0
  xxh3: ^1.2.0
  path: ^1.9.1
  collection: ^1.19.1
  meta: ^1.17.0
  glob: ^2.1.3
  watcher: ^1.1.2
  dart_style: ^3.1.2
  ansicolor: ^2.0.3
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  frontend_server_client: ^4.0.0
  yaml: ^3.1.3
  lints: ^6.0.0
  test: ^1.26.3
  hotreloader: ^4.3.0
